version: "3.7"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports: 
        - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: ''
      MYSQL_DATABASE: test
    command: --default-authentication-plugin=mysql_native_password