version: "3.7"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports: 
        - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "test"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
