DROP DATABASE IF EXISTS DBCOTACAO;
CREATE DATABASE DBCOTACAO;
USE DBCOTACAO;

CREATE TABLE COTACAO (
	IDCOTACAO INT NOT NULL AUTO_INCREMENT
    , DTCOTACAO DATE
    , VALOR NUMERIC(8,2)
    , PRIMARY KEY (IDCOTACAO)
);

CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(45)
    , VALOR NUMERIC(8,2)
    , PRIMARY KEY(IDPRODUTO)
);

CREATE TABLE VENDA (
	IDVENDA INT NOT NULL AUTO_INCREMENT
    , IDPRODUTO INT NOT NULL
    , DTVENDA DATE
    , VALOR_REAL NUMERIC(8,2)
    , VALOR_DOLAR NUMERIC(8,2)
    , PRIMARY KEY (IDVENDA)
    , FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (IDPRODUTO)
    );

INSERT INTO PRODUTO (NOME, VALOR)VALUES('CELULAR', 200);
INSERT INTO PRODUTO (NOME, VALOR)VALUES('TABLET', 350);

INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -5 DAY)), 4.09 - 0.55);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -4 DAY)), 4.09 - 0.45);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -3 DAY)), 4.09 - 0.35);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -2 DAY)), 4.09 - 0.25);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -1 DAY)), 4.09 - 0.15);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  0 DAY)), 4.09 - 0.05);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  1 DAY)), 4.09 + 0.15);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  2 DAY)), 4.09 + 0.25);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  3 DAY)), 4.09 + 0.35);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  4 DAY)), 4.09 + 0.45);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  5 DAY)), 4.09 + 0.55);



SELECT * FROM COTACAO;
SELECT * FROM PRODUTO;
SELECT * FROM VENDA;


DELIMITER $$

CREATE TRIGGER TR_INSERT_AI BEFORE INSERT ON VENDA FOR EACH ROW

BEGIN
    DECLARE DATA_COTACAO DATE;
    DECLARE VALOR_DOLAR NUMERIC(8,2);
    DECLARE VALOR_REAL NUMERIC(8,2);
    DECLARE VALOR_COTACAO  NUMERIC(8,2);

    SELECT DTCOTACAO INTO DATA_COTACAO FROM COTACAO WHERE DTCOTACAO = NEW.DTVENDA;
    
    IF ( DATA_COTACAO IS NULL ) THEN
        SIGNAL SQLSTATE "45000" SET MESSAGE_TEXT = "DATA PARA ESTA COTAÇÃO NÃO EXISTE";
    END IF;

    SELECT VALOR INTO VALOR_REAL FROM PRODUTO WHERE PRODUTO.IDPRODUTO = NEW.IDPRODUTO;

    SELECT VALOR INTO VALOR_COTACAO FROM COTACAO WHERE COTACAO.DTCOTACAO = NEW.DTVENDA;


    SET VALOR_DOLAR = VALOR_REAL / VALOR_COTACAO;
    
    SET NEW.VALOR_REAL = VALOR_REAL;
    SET NEW.VALOR_DOLAR = VALOR_DOLAR; 

END $$ 

DELIMITER ;

 ---- VERIFICAÇÃO ---
INSERT INTO VENDA VALUES (NULL,1,"2020-03-20",100,100); 
INSERT INTO VENDA VALUES (NULL,2,"2020-03-30",100,100); 
INSERT INTO VENDA VALUES (NULL,1,"2020-03-24",100,100); 
INSERT INTO VENDA VALUES (NULL,2,"2020-03-28",100,100); 

