/*
CRIAÇÃO DE FUNÇÕES 

DELIMITER $$
CREATE FUNCTION NOME_FUNCTION(ARG) RETURNS  TIPO 
BEGIN

    RETURN NOME_VARIAVEL;
END $$
DELIMITER ;


*/


SET GLOBAL log_bin_trust_function_creators = 1;

DELIMITER $$

CREATE FUNCTION FN_ADICAO (NUMBERA INT ,NUMBERB INT) RETURNS INT
BEGIN
    DECLARE TOTAL INT;
    
    SET TOTAL = NUMBERA + NUMBERB;

    RETURN TOTAL;
END $$

CREATE FUNCTION FN_SUBTRACAO (NUMBERA INT ,NUMBERB INT) RETURNS INT
BEGIN
    DECLARE TOTAL INT;
    
    SET TOTAL = NUMBERA - NUMBERB;

    RETURN TOTAL;
END $$

CREATE FUNCTION FN_MUILTIPLICACAO (NUMBERA INT ,NUMBERB INT) RETURNS INT
BEGIN
    DECLARE TOTAL INT;
    
    SET TOTAL = NUMBERA * NUMBERB;

    RETURN TOTAL;
END $$

CREATE FUNCTION FN_DIVISAO (NUMBERA INT ,NUMBERB INT) RETURNS INT
BEGIN
    DECLARE TOTAL INT;
    
    SET TOTAL = NUMBERA / NUMBERB;

    RETURN TOTAL;
END $$

CREATE FUNCTION FN_CALCULADORA(NUMBERA INT , OPERADOR VARCHAR(1) ,NUMBERB INT) RETURNS INT
BEGIN
    DECLARE TOTAL INT;
    
    IF OPERADOR = "+" THEN 
    	SET TOTAL = FN_ADICAO(NUMBERA,NUMBERB);
    END IF;
    IF OPERADOR = "-" THEN 
    	SET TOTAL = FN_SUBTRACAO(NUMBERA,NUMBERB);
    END IF;
    IF OPERADOR = "*" THEN 
    	SET TOTAL = FN_MUILTIPLICACAO(NUMBERA,NUMBERB);
    END IF;
    IF OPERADOR = "/" THEN 
    	SET TOTAL = FN_DIVISAO(NUMBERA,NUMBERB);
    END IF;
    
    RETURN TOTAL;
END $$

CREATE FUNCTION FN_PRIMO(NUMBERA INT) RETURNS TEXT
BEGIN

    DECLARE vCOUNT INT DEFAULT 0;
    DECLARE PRIMO INT DEFAULT 0;
    DECLARE STATUS_NUM text;
    
    WHILE (vCOUNT <> NUMBERA) DO

      IF ((NUMBERA % vCOUNT) = 0) THEN
        SET PRIMO = PRIMO + 1;
      END IF;

    IF PRIMO > 2 THEN
      SET STATUS_NUM = "NÃO É PRIMO";
    END IF;
    
    IF PRIMO < 3 THEN 
      SET STATUS_NUM = "É PRIMO";
    END IF;
    
    SET vCOUNT = vCOUNT + 1; 

  END WHILE;

    RETURN STATUS_NUM;

END $$



CREATE FUNCTION FN_IDADE(NASC DATE) RETURNS INT
BEGIN
    DECLARE RESULT INT;

    SET RESULT =  YEAR(NOW()) - YEAR(NASC);

    RETURN RESULT;
    
END $$


CREATE FUNCTION FN_NIVER(NASC DATE) RETURNS TEXT
BEGIN
    DECLARE DIA INT;
    DECLARE MES INT;
    DECLARE ANO INT;
    DECLARE BIRTHDAY TEXT;

    SET DIA = DAY(NASC);
    SET MES = MONTH(NASC);
    SET ANO = YEAR(NOW());
    SET BIRTHDAY = CONCAT(DIA,"/",MES,"/",ANO);

    RETURN  BIRTHDAY;
    
END $$

CREATE FUNCTION FN_ROMANO(NUMERO INT) RETURNS TEXT 
BEGIN
    DECLARE ROMANO TEXT;
    
  WHILE (NUMERO >= 1 ) DO 
    IF NUMERO >= 1 AND NUMERO <= 3 THEN
      SET ROMANO = CONCAT(ROMANO,"I");
      SET NUMERO = NUMERO - 1;
    ELSE IF NUMERO = 4 THEN
      SET ROMANO =  CONCAT(ROMANO, "IV");
      SET NUMERO = NUMERO - 4;
    ELSE IF NUMERO => 5 AND <= 8 THEN
      SET ROMANO = CONCAT(ROMANO,"V");
      SET NUMERO = NUMERO - 5;
    ELSE IF NUMERO = 9 THEN
      SET ROMANO = CONCAT(ROMANO,"IX");
      SET NUMERO = NUMERO - 9;
    ELSE IF NUMERO => 10 AND <= 39 THEN
      SET ROMANO = CONCAT(ROMANO,"X");
      SET NUMERO = NUMERO - 10;
    ELSE IF NUMERO => 40 AND <= 49 THEN
      SET ROMANO = CONCAT(ROMANO,"XL");
      SET NUMERO = NUMERO - 40;
     ELSE IF NUMERO => 50 AND <= 89 THEN
      SET ROMANO = CONCAT(ROMANO,"L");
      SET NUMERO = NUMERO - 50;
     ELSE IF NUMERO => 100 AND <= 399 THEN
      SET ROMANO = CONCAT(ROMANO,"C");
      SET NUMERO = NUMERO - 100;
    ELSE IF NUMERO => 400 AND <= 899 THEN
      SET ROMANO = CONCAT(ROMANO,"D");
      SET NUMERO = NUMERO - 500;
    ELSE IF NUMERO => 900 AND <= 3999 THEN
      SET ROMANO = CONCAT(ROMANO,"M");
      SET NUMERO = NUMERO - 1000;
    END IF;
  END WHILE; 

  RETURN ROMANO
END $$

DELIMITER ;


SELECT 
FN_ADICAO(10,10),
FN_SUBTRACAO(10,10),
FN_MUILTIPLICACAO(10,10),
FN_DIVISAO(10,10),
FN_CALCULADORA(10,"/",10),
FN_PRIMO(10),
FN_IDADE("1997-12-21"),
FN_NIVER("1997-12-21"),
FN_ROMANO(19)

