SET GLOBAL log_bin_trust_function_creators = 1;

DELIMITER $$
CREATE FUNCTION FN_QUINTODIA(pMES INT, pANO INT) RETURNS DATE
BEGIN
    DECLARE vDATAINICIAL DATE;
    DECLARE vCONTADOR INT;
   
    IF pMES BETWEEN 1 AND 12 THEN
        SET vDATAINICIAL = CONCAT(pANO, '-', pMES + 1, '-01');
       
        CASE dayofweek(vDATAINICIAL)
            WHEN 1 Then SET vCONTADOR = 5; -- DOMINGO
            WHEN 2 then SET vCONTADOR = 4; -- SEGUNDA
            ELSE SET vCONTADOR = 6;
        END CASE;
       
        SET vDATAINICIAL = DATE_ADD(vDATAINICIAL, INTERVAL vCONTADOR DAY);
    ELSE
        SET vDATAINICIAL = NULL;
    END IF;
   
    RETURN vDATAINICIAL;
END $$

CREATE PROCEDURE SP_GERA_FOLHA(ANO int, MES int)
BEGIN

	DELETE FROM FOLHA_PAGAMENTO WHERE ANO_REFERENCIA = ANO AND MES_REFERENCIA = MES;

    INSERT INTO FOLHA_PAGAMENTO (IDFUNCIONARIO, ANO_REFERENCIA, MES_REFERENCIA, DT_GERACAO, DT_PAGAMENTO, VALOR_BASE, AUXILIO_MEDICO, AUXILIO_TRANSPORTE, AUXILIO_ALIMENTACAO, BONUS_FUNCAO) 
    SELECT
         FUNCIONARIO.IDFUNCIONARIO
        , ANO
        , MES
        , NOW()
        , FN_QUINTODIA(MES, ANO)
        , FUNCIONARIO.SALARIO_BASE
        , 250
        , 150
        , 650
        , IFNULL((FUNCIONARIO.SALARIO_BASE * FUNCAO.BONUS) / 100, 0) AS VALOR_BONUS
    FROM
        FUNCIONARIO
    LEFT JOIN FUNCAO ON
    FUNCAO.IDFUNCAO = FUNCIONARIO.IDFUNCAO;
    
    SELECT * FROM FOLHA_PAGAMENTO;
    
END$$
DELIMITER ;


SELECT 
FOLHA_PAGAMENTO.*,
FUNCAO.NOME,
FUNCIONARIO.NOME
FROM FUNCIONARIO 
	  INNER JOIN FUNCAO ON 
    FUNCIONARIO.IDFUNCAO = FUNCAO.IDFUNCAO
    INNER JOIN FOLHA_PAGAMENTO ON 
    FOLHA_PAGAMENTO.IDFUNCIONARIO = FUNCIONARIO.IDFUNCIONARIO
    INNER JOIN DEPARTAMENTO ON 
    DEPARTAMENTO.IDDEPARTAMENTO = FUNCIONARIO.IDDEPARTAMENTO
ORDER BY 
	  FOLHA_PAGAMENTO.ANO_REFERENCIA,
    FOLHA_PAGAMENTO.MES_REFERENCIA,
    DEPARTAMENTO.IDDEPARTAMENTO,
    FUNCIONARIO.IDFUNCAO