SET SQL_SAFE_UPDATES = 0;

DROP DATABASE IF EXISTS ESPECULACAO;
CREATE DATABASE ESPECULACAO;
USE ESPECULACAO;

CREATE TABLE PAPEL (
    IDPAPEL INT PRIMARY KEY AUTO_INCREMENT NOT NULL
    ,NOME VARCHAR(100)
    ,VALOR NUMERIC(10,2)
    ,QTDE INT
);

CREATE TABLE INVESTIDOR (
    IDINVESTIDOR INT PRIMARY KEY AUTO_INCREMENT NOT NULL
    ,CAPITAL NUMERIC(10,2)
    ,NOME TEXT
); 

CREATE TABLE CARTEIRA (
      IDINVESTIDOR INT NOT NULL 
    , IDPAPEL INT NOT NULL 
    , QTDE INT 
    , VALOR NUMERIC(10,2)
    , LIMITE_INFERIOR_VALOR NUMERIC(10,2)
    , LIMITE_SUPERIOR_VALOR NUMERIC(10,2)
    , LIMITE_INFERIOR_PERC INT
    , FOREIGN KEY (IDPAPEL) REFERENCES PAPEL(IDPAPEL)
    , FOREIGN KEY (IDINVESTIDOR) REFERENCES INVESTIDOR(IDINVESTIDOR)
);

CREATE TABLE TRANSACAO (
    IDTRANSACAO INT PRIMARY KEY AUTO_INCREMENT NOT NULL
    IDINVESTIDOR INT NOT NULL 
   ,IDPAPEL INT NOT NULL 
   ,QTDE INT 
   ,VALOR NUMERIC(10,2)
   ,PROCESSADO ENUM("S","N")
   , DTTRANSACAO DATE 
);
