SET SQL_SAFE_UPDATES = 0;
SET global max_prepared_stmt_count = 16382;

DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
USE test;

CREATE TABLE IF NOT EXISTS USUARIO (
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT NOT NULL
    , NOME VARCHAR(45) NOT NULL
    , SENHA VARCHAR(45) NOT NULL
    , USUARIO_DB VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS MENSAGEM (
	IDMENSAGEM INT PRIMARY KEY AUTO_INCREMENT NOT NULL
    , TITULO VARCHAR(45)
    , MENSAGEM VARCHAR(200)
    , IDUSUARIO_REMETENTE INT NOT NULL
    , IDUSUARIO_DESTINATARIO  INT NOT NULL
    ,FOREIGN KEY (IDUSUARIO_REMETENTE) REFERENCES USUARIO(IDUSUARIO)
    ,FOREIGN KEY (IDUSUARIO_DESTINATARIO) REFERENCES USUARIO(IDUSUARIO)
);

CREATE VIEW VW_MESSAGEM AS 
SELECT 
USUARIO.NOME,
MENSAGEM.TITULO,
MENSAGEM.MENSAGEM 
FROM MENSAGEM 
	INNER JOIN USUARIO ON
    MENSAGEM.IDUSUARIO_REMETENTE = USUARIO.IDUSUARIO
WHERE 
	USUARIO.NOME = SUBSTR(CURRENT_USER(), 1, (LOCATE("@", CURRENT_USER()) - 1));

DELIMITER $$

CREATE PROCEDURE add_USUARIO (USUARIO_DB varchar(100), SENHA_DB VARCHAR(100))
BEGIN
	DECLARE vUSUARIO VARCHAR(100);
    DECLARE vHOST CHAR(14);
    DECLARE vSENHA CHAR(14);

  	SET vHOST = '@\'localhost\'';
    SET vUSUARIO = CONCAT('\'', USUARIO_DB, '\'');
    SET vSENHA = CONCAT('\'', SENHA_DB, '\'');
    SET @vSQL = CONCAT('CREATE USER ', vUSUARIO, vHOST, ' IDENTIFIED BY ', vSENHA);
    
    PREPARE stmt FROM @vSQL;
	EXECUTE stmt;
	DEALLOCATE PREPARE stmt;
	
	INSERT INTO USUARIO (NOME, SENHA, USUARIO_DB)VALUES(USUARIO_DB, SENHA_DB, USUARIO_DB);

END $$

CREATE TRIGGER TR_VW_MESSAGEM_AI AFTER INSERT ON MENSAGEM FOR EACH ROW
BEGIN 	
		DECLARE USER_LOGADO TEXT ;
        DECLARE USUARIO_MENSAGEM INT;
        DECLARE ID_USUARIO_LOGADO INT;
        
        SET USER_LOGADO = SUBSTR(CURRENT_USER(), 1, LOCATE("@", CURRENT_USER()) - 1);
        
        SELECT
        MENSAGEM.IDUSUARIO_REMETENTE
        INTO USUARIO_MENSAGEM
        FROM MENSAGEM
			INNER JOIN USUARIO ON
            MENSAGEM.IDUSUARIO_REMETENTE = USUARIO.IDUSUARIO
		WHERE 
			USUARIO.NOME = USER_LOGADO LIMIT 1;
             
        SELECT
        IDUSUARIO
        INTO ID_USUARIO_LOGADO
        FROM USUARIO
		WHERE 
			NOME = USER_LOGADO LIMIT 1;    
        
        IF ID_USUARIO_LOGADO <> NEW.IDUSUARIO_REMETENTE THEN 
		  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "VOCÊ NÃO NÃO TEM AUTORIZAÇÃO PARA CRIAR ALGO COM ESSE USUARIO";
        END IF ;
        
END $$

CREATE TRIGGER TR_VW_MESSAGEM_AD AFTER DELETE ON MENSAGEM FOR EACH ROW
BEGIN 	
		DECLARE USER_LOGADO TEXT ;
        DECLARE USUARIO_MENSAGEM INT;
        DECLARE ID_USUARIO_LOGADO INT;
        
        SET USER_LOGADO = SUBSTR(CURRENT_USER(), 1, LOCATE("@", CURRENT_USER()) - 1);
        
        SELECT
        MENSAGEM.IDUSUARIO_REMETENTE
        INTO USUARIO_MENSAGEM
        FROM MENSAGEM
			INNER JOIN USUARIO ON
            MENSAGEM.IDUSUARIO_REMETENTE = USUARIO.IDUSUARIO
		WHERE 
			USUARIO.NOME = USER_LOGADO LIMIT 1;
             
        SELECT
        IDUSUARIO
        INTO ID_USUARIO_LOGADO
        FROM USUARIO
		WHERE 
			NOME = USER_LOGADO LIMIT 1;    
        
        IF ID_USUARIO_LOGADO <> OLD.IDUSUARIO_REMETENTE THEN 
		  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "VOCÊ NÃO NÃO TEM AUTORIZAÇÃO PARA CRIAR ALGO COM ESSE USUARIO";
        END IF ;
        
END $$

CREATE TRIGGER TR_VW_MESSAGEM_AU AFTER UPDATE ON MENSAGEM FOR EACH ROW
BEGIN 	
		DECLARE USER_LOGADO TEXT ;
        DECLARE USUARIO_MENSAGEM INT;
        DECLARE ID_USUARIO_LOGADO INT;
        
        SET USER_LOGADO = SUBSTR(CURRENT_USER(), 1, LOCATE("@", CURRENT_USER()) - 1);
        
        SELECT
        MENSAGEM.IDUSUARIO_REMETENTE
        INTO USUARIO_MENSAGEM
        FROM MENSAGEM
			INNER JOIN USUARIO ON
            MENSAGEM.IDUSUARIO_REMETENTE = USUARIO.IDUSUARIO
		WHERE 
			USUARIO.NOME = USER_LOGADO LIMIT 1;
             
        SELECT
        IDUSUARIO
        INTO ID_USUARIO_LOGADO
        FROM USUARIO
		WHERE 
			NOME = USER_LOGADO LIMIT 1;    
        
        IF ID_USUARIO_LOGADO <> NEW.IDUSUARIO_REMETENTE THEN 
		  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "VOCÊ NÃO NÃO TEM AUTORIZAÇÃO PARA CRIAR ALGO COM ESSE USUARIO";
        END IF ;
        
        IF ID_USUARIO_LOGADO <> OLD.IDUSUARIO_REMETENTE THEN 
		  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "VOCÊ NÃO NÃO TEM AUTORIZAÇÃO PARA CRIAR ALGO COM ESSE USUARIO";
        END IF ;
        
END $$

DELIMITER ;

-- CALL add_USUARIO('JESS', '12345');

-- GRANT INSERT ON test.* TO 'MARIA'@'localhost' IDENTIFIED BY '1234';

-- FLUSH PRIVILEGES;  

SELECT * FROM USUARIO;

SELECT * FROM MENSAGEM;

INSERT INTO USUARIO VALUES (1,'JADSON','123','JADSON');
INSERT INTO USUARIO VALUES (2,'root','123','root');

-- SELECT * FROM mysql.user;

INSERT INTO MENSAGEM VALUE (4,"OI","Meu nome é root",1,1);


SELECT * FROM VW_MESSAGEM;

