DROP DATABASE IF EXISTS STARTUP;
CREATE DATABASE STARTUP;
USE STARTUP;

CREATE TABLE ASSOCIADO (
	 IDASSOCIADO INT PRIMARY KEY AUTO_INCREMENT NOT NULL
    , NOME VARCHAR(200)
    , SEXO ENUM("M","F")
    , IDADE INT
);
CREATE TABLE DRONE(
	 IDDRONE INT PRIMARY KEY AUTO_INCREMENT NOT NULL
    ,NOME VARCHAR(200)
);

CREATE TABLE PONTOS_INTERESSE(
	  IDPONTOS_INTERESSE INT PRIMARY KEY AUTO_INCREMENT NOT NULL
    , LATITUDE INT NOT NULL
    , LONGITUDE INT NOT NULL
    , IDASSOCIADO INT NOT NULL
    , FOREIGN KEY (IDASSOCIADO) REFERENCES ASSOCIADO(IDASSOCIADO)
 );
 
CREATE TABLE OPERADOR (
	 IDOPERADOR INT PRIMARY KEY AUTO_INCREMENT NOT NULL
    ,NOME VARCHAR(200)
    ,SEXO ENUM("M","F")
);
CREATE TABLE CHAMADO(
	 IDCHAMADO INT PRIMARY KEY AUTO_INCREMENT NOT NULL
    ,TIPO ENUM("ESCOLTA","VIGILANCIA") NOT NULL
	,IDASSOCIADO INT NOT NULL
	,IDPONTOS_INTERESSE INT NOT NULL
    ,IDDRONE INT NOT NULL
    ,IDOPERADOR INT NOT NULL
    ,DTTIME_SOLICITACAO DATETIME NOT NULL 
    ,DTTIME_ACIONAMENTO DATETIME
    ,DTTIME_CHEGADA DATETIME
    ,DTTIME_LIBERACAO DATETIME
	,FOREIGN KEY (IDOPERADOR) REFERENCES OPERADOR(IDOPERADOR)
    ,FOREIGN KEY (IDASSOCIADO) REFERENCES ASSOCIADO(IDASSOCIADO)
    ,FOREIGN KEY (IDPONTOS_INTERESSE) REFERENCES PONTOS_INTERESSE(IDPONTOS_INTERESSE)
	,FOREIGN KEY (IDDRONE) REFERENCES DRONE(IDDRONE)
);
CREATE TABLE IMAGEM (
	 IDIMAGEM INT PRIMARY KEY AUTO_INCREMENT NOT NULL
    , NOME VARCHAR(255)
	, IDCHAMADO INT NOT NULL
    , FOREIGN KEY (IDCHAMADO) REFERENCES CHAMADO(IDCHAMADO)
);
CREATE TABLE VIDEO (
	 IDVIDEO INT PRIMARY KEY AUTO_INCREMENT NOT NULL
    , NOME VARCHAR(255)
	, IDCHAMADO INT NOT NULL
    , FOREIGN KEY (IDCHAMADO) REFERENCES CHAMADO(IDCHAMADO)
);


INSERT INTO ASSOCIADO (IDASSOCIADO, NOME,SEXO,IDADE) VALUES(NULL,"JADSON DOS SANTOS SILVA","M",21);
INSERT INTO ASSOCIADO (IDASSOCIADO, NOME,SEXO,IDADE) VALUES(NULL,"CASSIA BARBOSA DOS SANTOS","F",43);
INSERT INTO ASSOCIADO (IDASSOCIADO, NOME,SEXO,IDADE) VALUES(NULL,"CARLOS ALBERTO SUZART DA SILVA","M",47);
INSERT INTO ASSOCIADO (IDASSOCIADO, NOME,SEXO,IDADE) VALUES(NULL,"BRUNA FARIAS","F",26);

INSERT INTO DRONE (IDDRONE, NOME) VALUES(NULL,"FFFFF1");
INSERT INTO DRONE (IDDRONE, NOME) VALUES(NULL,"FFFFF2");
INSERT INTO DRONE (IDDRONE, NOME) VALUES(NULL,"FFFFF3");
INSERT INTO DRONE (IDDRONE, NOME) VALUES(NULL,"FFFFF4");

INSERT INTO PONTOS_INTERESSE (IDPONTOS_INTERESSE, LATITUDE,LONGITUDE,IDASSOCIADO) VALUES(NULL,27.5733153,-48.5287276,1);
INSERT INTO PONTOS_INTERESSE (IDPONTOS_INTERESSE, LATITUDE,LONGITUDE,IDASSOCIADO) VALUES(NULL,27.5733153,-48.5287276,2);
INSERT INTO PONTOS_INTERESSE (IDPONTOS_INTERESSE, LATITUDE,LONGITUDE,IDASSOCIADO) VALUES(NULL,27.5733153,-48.5287276,3);
INSERT INTO PONTOS_INTERESSE (IDPONTOS_INTERESSE, LATITUDE,LONGITUDE,IDASSOCIADO) VALUES(NULL,-27.629577,-48.4783447,4);

INSERT INTO OPERADOR (IDOPERADOR, NOME,SEXO) VALUES(NULL,"PEDRO ALVES","M");

INSERT INTO CHAMADO 
(IDCHAMADO, TIPO,IDASSOCIADO,IDPONTOS_INTERESSE,IDDRONE,IDOPERADOR,DTTIME_SOLICITACAO,DTTIME_ACIONAMENTO,DTTIME_CHEGADA,DTTIME_LIBERACAO)  
VALUES (NULL, "VIGILANCIA",1,1,1,1,"2020-06-16 20:38:56","2020-06-16 20:38:16","2020-06-17 21:38:16","2020-06-18 22:38:18");

INSERT INTO IMAGEM (IDIMAGEM,NOME,IDCHAMADO) VALUES (NULL,"IMAGEM-CASA-DO-JADSON.png",1);
INSERT INTO VIDEO (IDVIDEO,NOME,IDCHAMADO) VALUES (NULL,"IMAGEM-CASA-DO-JADSON.mp4",1);

CREATE VIEW VW_TEMPO_ATENDIMENTO AS SELECT 
DATEDIFF(DTTIME_SOLICITACAO,DTTIME_ACIONAMENTO) AS "TEMPO DE UM ATENDIMENTO",
DATEDIFF(DTTIME_ACIONAMENTO,DTTIME_CHEGADA) AS "TENesta segunda etapa você deve desenvolver uma view para calcular os tempo de atendimento de vigilancia.MPO DE DESLOCAMENTO",
DATEDIFF(DTTIME_CHEGADA,DTTIME_LIBERACAO) AS "TEMPO DE ATENDIMENTO",
DATEDIFF(DTTIME_ACIONAMENTO,DTTIME_LIBERACAO) AS "TEMPO TOTAL ATENDIMENTO"
FROM CHAMADO
WHERE  
 TIPO = "VIGILANCIA" ;


SELECT * FROM VW_TEMPO_ATENDIMENTO;
